name: CI/CD - API Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with :
          fetch-depth : 0

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installation de uv
        run: pip install uv

      - name: Installation des dépendances
        run: uv sync --frozen

      - name: Lancement des tests avec couverture
        run: uv run pytest --cov=src --cov-report=term-missing -v

      - name: Construction de l'image Docker
        run: docker build -t home-credit-api .

      - name: Déploiement sur Hugging Face Spaces
        if: github.ref == 'refs/heads/develop'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME

          git push space HEAD:main --force